name: Star Platinum

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # check out repository code and setup node
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@3c2fe8c59284aae169107529dce6c78999f48956
        with:
          version: 6.10.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'pnpm'

      - name: Install dependencies and test
        run: |
          pnpm i
          pnpm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@3c2fe8c59284aae169107529dce6c78999f48956
        with:
          version: 6.10.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies and build
        run: |
          pnpm i
          mkdir ./dist
          cp package.json ./dist
          cp -r .releaserc ./dist
          pnpm run build
