name: Star Platinum

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # check out repository code and setup node
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@3c2fe8c59284aae169107529dce6c78999f48956
        with:
          version: 6.10.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies and test
        run: |
          pnpm i
          pnpm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@3c2fe8c59284aae169107529dce6c78999f48956
        with:
          version: 6.10.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies and build
        run: |
          pnpm i
          mkdir ./dist
          cp package.json ./dist
          cp -r .releaserc ./dist
          pnpm run build

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@3c2fe8c59284aae169107529dce6c78999f48956
        with:
          version: 6.10.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Download build result
        uses: actions/download-artifact@v2
        with:
          name: bundle
          path: dist

      - name: Release
        run: |
          pnpm add -g semantic-release
          pnpm add -g @semantic-release/changelog
          pnpm add -g @semantic-release/git
          semantic-release

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
